import { Octokit } from "@octokit/rest";
import { REPO_NAME } from "@/lib/constants";
import type { LearningCommitPayload } from "@/lib/types";

/**
 * Ensure the dev-learning-log repo exists for the authenticated user.
 * If it doesn't, create it with auto_init.
 */
export async function ensureRepo(token: string): Promise<string> {
  const octokit = new Octokit({ auth: token });
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const login = user.login;

  try {
    await octokit.rest.repos.get({ owner: login, repo: REPO_NAME });
  } catch (e: unknown) {
    const err = e as { status?: number };
    if (err.status === 404) {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: REPO_NAME,
        description:
          "My developer learning journal — auto-generated by RoadmapHub 🚀",
        private: false,
        auto_init: true,
      });
    } else if (err.status !== 422) {
      throw e;
    }
  }

  return `https://github.com/${login}/${REPO_NAME}`;
}

/**
 * Commit a learning note (and optional practice files) to the repo.
 *
 * File structure in the repo mirrors roadmap.sh's structure:
 *   {roadmapSlug}/{topicSlug}.md
 *
 * e.g. backend/acid.md, frontend/html.md, devops/docker.md
 */
export async function commitLearning(
  token: string,
  payload: LearningCommitPayload,
  markdownContent: string
): Promise<string> {
  const octokit = new Octokit({ auth: token });
  
  // --- 0. Ensure repo exists (it might have been deleted) ---
  await ensureRepo(token);

  const { data: user } = await octokit.rest.users.getAuthenticated();
  const login = user.login;

  const { topic, commitMessage, practiceFiles } = payload;

  // Use the real roadmap slug and topic slug from the DOM
  const domainSlug = topic.roadmapSlug || "misc";
  const topicSlug = topic.topicSlug || slugify(topic.topicName);
  const notePath = `${domainSlug}/${topicSlug}.md`;

  // --- 1. Commit the markdown note ---
  console.log(`[RoadmapHub] 📝 Committing note to ${login}/${REPO_NAME}/${notePath}`);
  let fileSha: string | undefined;
  try {
    // Direct URL construction to bypass Octokit's automatic slash encoding
    const { data: existing } = await octokit.request({
      method: "GET",
      url: `/repos/${login}/${REPO_NAME}/contents/${notePath}`,
    }) as any;
    if (!Array.isArray(existing) && existing.type === "file") {
      fileSha = existing.sha;
    }
  } catch (e) {
    console.debug("[RoadmapHub] Note does not exist yet (or 404):", notePath);
  }

  const { data: commitResult } = await octokit.request({
    method: "PUT",
    url: `/repos/${login}/${REPO_NAME}/contents/${notePath}`,
    data: {
      message: commitMessage || `learn(${domainSlug}): ${topic.topicName}`,
      content: btoa(unescape(encodeURIComponent(markdownContent))),
      sha: fileSha,
    }
  }) as any;

  // --- 2. Commit practice files (if any) ---
  for (const file of practiceFiles) {
    const practicePath = `${domainSlug}/${topicSlug}-practice/${file.name}`;
    console.log(`[RoadmapHub] 📂 Committing practice file: ${practicePath}`);
    let practiceSha: string | undefined;
    try {
      const { data: existing } = await octokit.request({
        method: "GET",
        url: `/repos/${login}/${REPO_NAME}/contents/${practicePath}`,
      }) as any;
      if (!Array.isArray(existing) && existing.type === "file") {
        practiceSha = existing.sha;
      }
    } catch {
      // new file
    }

    await octokit.request({
      method: "PUT",
      url: `/repos/${login}/${REPO_NAME}/contents/${practicePath}`,
      data: {
        message: `practice(${domainSlug}): ${file.name} — ${topic.topicName}`,
        content: file.content, // already base64
        sha: practiceSha,
      }
    });
  }

  // --- 3. Update README.md index ---
  await updateReadme(octokit, login, topic.topicName, domainSlug, notePath, topic.totalTopics);

  return commitResult.content?.html_url || "";
}

/**
 * Update the repo README with a new learning entry and a progress dashboard.
 */
async function updateReadme(
  octokit: Octokit,
  login: string,
  topicName: string,
  domainSlug: string,
  notePath: string,
  totalTopics: number = 0
) {
  let readmeSha: string | undefined;
  let current = "";

  try {
    const { data: readmeFile } = await octokit.request({
      method: "GET",
      url: `/repos/${login}/${REPO_NAME}/contents/README.md`,
    }) as any;
    if (!Array.isArray(readmeFile) && readmeFile.type === "file" && readmeFile.content) {
      readmeSha = readmeFile.sha;
      current = decodeURIComponent(escape(atob(readmeFile.content.replace(/\n/g, ""))));
    }
  } catch {
    current = `# 🗺️ Dev Learning Log\n\nAuto-generated by [RoadmapHub](https://github.com) — tracking my journey on [roadmap.sh](https://roadmap.sh).\n\n---\n\n`;
  }

  const date = new Date().toISOString().split("T")[0];
  const newEntry = `- [${topicName}](${notePath}) — ${date}`;
  const domainHeader = `### ${formatDomain(domainSlug)}`;

  // 1. Update the learning log entries
  if (!current.includes(newEntry)) {
    if (current.includes(domainHeader)) {
      current = current.replace(domainHeader, `${domainHeader}\n${newEntry}`);
    } else {
      current += `\n${domainHeader}\n${newEntry}\n`;
    }
  }

  // 2. Persist total count to storage for future dashboard updates
  if (totalTopics > 0) {
    const stored = await chrome.storage.local.get(["roadmap_totals"]);
    const totals = stored.roadmap_totals || {};
    totals[domainSlug] = totalTopics;
    await chrome.storage.local.set({ roadmap_totals: totals });
  }

  const allTotals = (await chrome.storage.local.get(["roadmap_totals"])).roadmap_totals || {};

  // 3. Generate/Update Progress Dashboard
  try {
    current = updateDashboard(current, domainSlug, totalTopics, allTotals);
  } catch (error) {
    console.warn("[RoadmapHub] Error updating progress dashboard in README:", error);
    // Continue anyway to ensure the learning note is committed
  }

  await octokit.request({
    method: "PUT",
    url: `/repos/${login}/${REPO_NAME}/contents/README.md`,
    data: {
      message: `docs: update README — ${topicName} (Progress: ${domainSlug})`,
      content: btoa(unescape(encodeURIComponent(current))),
      sha: readmeSha,
    }
  });
}

/**
 * Parses the README, calculates progress, and updates the dashboard section.
 * Much more robust line-by-line parsing.
 */
function updateDashboard(
  content: string,
  currentDomain: string,
  currentTotal: number,
  cachedTotals: Record<string, number> = {}
): string {
  const DASHBOARD_START = "## 📊 Progress Dashboard";
  const DASHBOARD_END = "---";

  console.log(`[RoadmapHub] 📊 Updating dashboard. Domain: ${currentDomain}, Total: ${currentTotal}`);

  const lines = content.split(/\r?\n/);
  const domainData: Record<string, { completed: number; total: number }> = {};
  
  let currentParserDomain = "";
  let currentParserItems = 0;

  for (const line of lines) {
    const headerMatch = line.match(/^#{1,3}\s+(.+)$/);
    if (headerMatch) {
      // If we were tracking a domain, save it now
      if (currentParserDomain && !currentParserDomain.includes("Dashboard")) {
        const slug = currentParserDomain.toLowerCase().replace(/\s+/g, "-");
        const cachedTotal = cachedTotals[slug] || 0;
        domainData[slug] = {
          completed: currentParserItems,
          total: (slug === currentDomain && currentTotal > 0) 
            ? currentTotal 
            : (cachedTotal > 0 ? cachedTotal : currentParserItems)
        };
      }
      currentParserDomain = headerMatch[1].trim();
      currentParserItems = 0;
    } else if (line.trim().startsWith("- ")) {
      currentParserItems++;
    }
  }

  // Save the last domain found
  if (currentParserDomain && !currentParserDomain.includes("Dashboard")) {
    const slug = currentParserDomain.toLowerCase().replace(/\s+/g, "-");
    const cachedTotal = cachedTotals[slug] || 0;
    domainData[slug] = {
      completed: currentParserItems,
      total: (slug === currentDomain && currentTotal > 0) 
        ? currentTotal 
        : (cachedTotal > 0 ? cachedTotal : currentParserItems)
    };
  }

  // Ensure current domain is at least tracked if not found or count is wrong
  if (currentTotal > 0) {
    if (!domainData[currentDomain]) {
      domainData[currentDomain] = { completed: 1, total: currentTotal };
    } else {
      domainData[currentDomain].total = currentTotal;
    }
  }

  if (Object.keys(domainData).length === 0) {
    console.log("[RoadmapHub] No domains found to build dashboard table.");
    return content; 
  }

  // Build the dashboard table
  let dashboard = `\n${DASHBOARD_START}\n\n`;
  dashboard += `| Roadmap | Progress | Completed | Remaining |\n`;
  dashboard += `| :--- | :--- | :--- | :--- |\n`;

  const sortedDomains = Object.keys(domainData).sort();
  for (const slug of sortedDomains) {
    const data = domainData[slug];
    const percentage = Math.round((data.completed / (data.total || 1)) * 100);
    const progressBar = `![${percentage}%](https://geps.dev/progress/${percentage})`;
    const remaining = Math.max(0, data.total - data.completed);
    const domainLink = `[${formatDomain(slug)}](./${slug})`;
    
    dashboard += `| ${domainLink} | ${progressBar} | ${data.completed}/${data.total} | ${remaining} |\n`;
  }
  dashboard += `\n`;

  // Insert or replace the dashboard section
  if (content.includes(DASHBOARD_START)) {
    const parts = content.split(DASHBOARD_START);
    // Find the end separator after the dashboard start
    const dashboardAndRest = parts[1];
    const restParts = dashboardAndRest.split(DASHBOARD_END);
    restParts.shift(); // remove the table section
    return parts[0].trim() + "\n" + dashboard + DASHBOARD_END + "\n" + restParts.join(DASHBOARD_END).trim();
  } else {
    // Insert dashboard after the first header (usually the title)
    const firstHeaderMatch = content.match(/^#\s+.+$/m);
    if (firstHeaderMatch && firstHeaderMatch.index !== undefined) {
      const endOfTitleLine = content.indexOf("\n", firstHeaderMatch.index);
      if (endOfTitleLine !== -1) {
        return content.slice(0, endOfTitleLine).trim() + "\n" + dashboard + DASHBOARD_END + "\n\n" + content.slice(endOfTitleLine).trim();
      }
    }
    return content.trim() + "\n\n" + dashboard + DASHBOARD_END + "\n";
  }
}

/** Simple slugify for fallback */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Format domain slug to display name */
function formatDomain(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
