import { Octokit } from "@octokit/rest";
import { REPO_NAME, GITHUB_ERRORS } from "@/lib/constants";
import type { LearningCommitPayload } from "@/lib/types";
import type { ProgressStore } from "@/lib/progressStore";
import { slugify } from "@/lib/utils";

// ========== Repo confirmation helpers ==========

async function isRepoConfirmed(): Promise<boolean> {
  const r = await chrome.storage.local.get("repo_confirmed");
  return !!r.repo_confirmed;
}

async function markRepoConfirmed(): Promise<void> {
  await chrome.storage.local.set({ repo_confirmed: true });
}

// ========== Encoding helpers ==========

function encodeUTF8(str: string): string {
  const bytes = new TextEncoder().encode(str);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

function decodeUTF8(base64: string): string {
  const binary = atob(base64.replace(/\s/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return new TextDecoder().decode(bytes);
}

// ========== GitHub error translation ==========

/**
 * Convert a raw GitHub API error into a user-readable message.
 */
export function translateGitHubError(e: unknown): string {
  const err = e as { status?: number; message?: string };
  if (err.status && GITHUB_ERRORS[err.status]) {
    return GITHUB_ERRORS[err.status];
  }
  if (err.message?.includes("rate limit")) {
    return GITHUB_ERRORS[403];
  }
  if (err.message?.includes("Bad credentials") || err.message?.includes("Unauthorized")) {
    return GITHUB_ERRORS[401];
  }
  return err.message || "An unexpected GitHub error occurred. Please try again.";
}

// ========== File metadata ==========

async function fetchFileMetadata(
  token: string,
  owner: string,
  repo: string,
  path: string
): Promise<{ sha?: string; content?: string } | null> {
  try {
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
      {
        headers: {
          Authorization: `token ${token}`,
          Accept: "application/vnd.github.v3+json",
        },
      }
    );
    if (response.status === 404) return null;
    if (!response.ok) return null;
    const data = await response.json();
    if (Array.isArray(data)) return null;
    return { sha: data.sha, content: data.content };
  } catch {
    return null;
  }
}

// ========== Repo management ==========

export async function ensureRepo(token: string): Promise<string> {
  if (await isRepoConfirmed()) return "";

  const octokit = new Octokit({ auth: token });
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const login = user.login;

  // Persist fresh username every time we confirm the repo
  await chrome.storage.local.set({ gh_username: login });

  try {
    await octokit.rest.repos.get({ owner: login, repo: REPO_NAME });
    await markRepoConfirmed();
  } catch (e: unknown) {
    const err = e as { status?: number };
    if (err.status === 404) {
      const defaultReadme = `# 🗺️ Dev Learning Log\n\n> Automatically tracked by [RoadmapHub](https://github.com/Harshabhi6129/roadmaphub-extension)  \n> Every topic I complete on [roadmap.sh](https://roadmap.sh) gets committed here automatically.\n\n<!-- ROADMAPHUB:DASHBOARD:START -->\n<!-- ROADMAPHUB:DASHBOARD:END -->\n\n---\n\n## 📖 Topics by Roadmap\n\n_Learning notes will appear here organized by roadmap domain as you commit topics._\n\n`;
      await octokit.rest.repos.createForAuthenticatedUser({
        name: REPO_NAME,
        description: "My developer learning journal — auto-generated by RoadmapHub 🚀",
        private: false,
        auto_init: false,
      });
      await new Promise(r => setTimeout(r, 1000));
      await octokit.rest.repos.createOrUpdateFileContents({
        owner: login,
        repo: REPO_NAME,
        path: "README.md",
        message: "init: create dev-learning-log with RoadmapHub",
        content: encodeUTF8(defaultReadme),
      });
      await markRepoConfirmed();
    } else if (err.status !== 422) {
      throw e;
    }
  }

  return `https://github.com/${login}/${REPO_NAME}`;
}

// ========== Commit learning note ==========

export async function commitLearning(
  token: string,
  payload: LearningCommitPayload,
  markdownContent: string,
  repoName: string = REPO_NAME
): Promise<string> {
  const octokit = new Octokit({ auth: token });
  await ensureRepo(token);

  // Always use fresh username from GitHub to handle account renames
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const login = user.login;
  // Keep stored username in sync
  await chrome.storage.local.set({ gh_username: login });

  const { topic, commitMessage, practiceFiles } = payload;
  const domainSlug = topic.roadmapSlug || "misc";
  const topicSlug = topic.topicSlug || slugify(topic.topicName);
  const notePath = `${domainSlug}/${topicSlug}.md`;

  const existingFile = await fetchFileMetadata(token, login, repoName, notePath);

  try {
    const { data: commitResult } = await octokit.request(
      "PUT /repos/{owner}/{repo}/contents/{path+}",
      {
        owner: login,
        repo: repoName,
        path: notePath,
        message: commitMessage || `learn(${domainSlug}): ${topic.topicName}`,
        content: encodeUTF8(markdownContent),
        sha: existingFile?.sha,
      }
    );

    // Commit practice files in parallel
    if (practiceFiles.length > 0) {
      await Promise.all(
        practiceFiles.map(async (file) => {
          const practicePath = `${domainSlug}/${topicSlug}-practice/${file.name}`;
          const existingPractice = await fetchFileMetadata(token, login, repoName, practicePath);
          await octokit.request("PUT /repos/{owner}/{repo}/contents/{path+}", {
            owner: login,
            repo: repoName,
            path: practicePath,
            message: `practice(${domainSlug}): ${file.name} — ${topic.topicName}`,
            content: file.content,
            sha: existingPractice?.sha,
          });
        })
      );
    }

    return (commitResult as any).content?.html_url || "";
  } catch (e: any) {
    if (e.status === 404) {
      // Repo may have been deleted — clear flag and retry once
      await chrome.storage.local.remove("repo_confirmed");
      return commitLearning(token, payload, markdownContent, repoName);
    }
    throw new Error(translateGitHubError(e));
  }
}

// ========== README dashboard ==========

export async function updateReadme(
  token: string,
  login: string,
  progressStore: ProgressStore,
  repoName: string = REPO_NAME
): Promise<void> {
  const octokit = new Octokit({ auth: token });
  const readmeData = await fetchFileMetadata(token, login, repoName, "README.md");
  if (!readmeData) return;

  const currentContent = decodeUTF8(readmeData.content || "");
  const MARKER_REGEX =
    /<!-- ROADMAPHUB:DASHBOARD:START -->[\s\S]*?<!-- ROADMAPHUB:DASHBOARD:END -->/;
  const newDashboard = buildDashboard(progressStore);

  let updatedContent: string;
  if (MARKER_REGEX.test(currentContent)) {
    updatedContent = currentContent.replace(MARKER_REGEX, newDashboard);
  } else {
    const firstHeadingEnd = currentContent.indexOf("\n", currentContent.search(/^#\s/m));
    if (firstHeadingEnd !== -1) {
      updatedContent =
        currentContent.slice(0, firstHeadingEnd + 1) +
        "\n" + newDashboard + "\n\n" +
        currentContent.slice(firstHeadingEnd + 1);
    } else {
      updatedContent = newDashboard + "\n\n" + currentContent;
    }
  }

  try {
    await octokit.request("PUT /repos/{owner}/{repo}/contents/{path+}", {
      owner: login,
      repo: repoName,
      path: "README.md",
      message: "docs: update dashboard stats across all roadmaps",
      content: encodeUTF8(updatedContent),
      sha: readmeData.sha,
    });
  } catch (e: any) {
    if (e.status === 404) await chrome.storage.local.remove("repo_confirmed");
    console.error("[RoadmapHub] Failed to update README dashboard:", translateGitHubError(e));
  }
}

// ========== Reinstall sync ==========

/**
 * Scan the user's dev-learning-log repo and return a map of
 * { roadmapSlug -> topicSlugs[] } derived from committed .md files.
 * Used to rebuild committedSlugs after extension reinstall.
 */
export async function syncCommittedSlugsFromGitHub(
  token: string,
  repoName: string = REPO_NAME
): Promise<Record<string, string[]>> {
  const octokit = new Octokit({ auth: token });

  // Always get fresh username
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const login = user.login;
  await chrome.storage.local.set({ gh_username: login });

  try {
    const { data: tree } = await octokit.rest.git.getTree({
      owner: login,
      repo: repoName,
      tree_sha: "HEAD",
      recursive: "1",
    });

    const result: Record<string, string[]> = {};

    for (const item of tree.tree) {
      if (!item.path || item.type !== "blob") continue;
      // Match "roadmap/topic.md" — ignore README.md and practice directories
      const match = item.path.match(/^([^/]+)\/([^/]+)\.md$/);
      if (!match) continue;
      const [, roadmapSlug, topicSlug] = match;
      if (topicSlug.toLowerCase() === "readme") continue;
      if (!result[roadmapSlug]) result[roadmapSlug] = [];
      result[roadmapSlug].push(topicSlug);
    }

    return result;
  } catch (e: any) {
    if (e.status === 404) return {}; // Repo doesn't exist yet — that's fine
    throw new Error(translateGitHubError(e));
  }
}

// ========== Dashboard builder ==========

function buildDashboard(store: ProgressStore): string {
  const slugs = Object.keys(store)
    .filter(k => store[k].total > 0)
    .sort((a, b) => store[b].progressPercent - store[a].progressPercent);

  if (slugs.length === 0) {
    return "<!-- ROADMAPHUB:DASHBOARD:START -->\n<!-- ROADMAPHUB:DASHBOARD:END -->";
  }

  const totalCompleted = slugs.reduce((s, k) => s + store[k].completed, 0);
  const totalTopics = slugs.reduce((s, k) => s + store[k].total, 0);
  const overallPct = totalTopics > 0
    ? Math.min(100, Math.round((totalCompleted / totalTopics) * 100))
    : 0;
  const today = new Date().toISOString().split("T")[0];
  const unslugify = (slug: string) =>
    slug.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");

  let out = `<!-- ROADMAPHUB:DASHBOARD:START -->\n\n`;
  out += `## 📊 Progress Dashboard\n\n`;
  out += `> Tracked by [RoadmapHub](https://github.com/Harshabhi6129/roadmaphub-extension) &nbsp;·&nbsp; Last updated: \`${today}\`\n\n`;
  out += `<div align="center">\n\n`;
  out += `**Overall Progress across all roadmaps**\n\n`;
  out += `![Overall Progress](${getBarUrl(overallPct, `Overall ${overallPct}%`)})\n\n`;
  out += `| 📚 Roadmaps | ✅ Completed | 🎯 Total | 📈 Overall |\n`;
  out += `|:-----------:|:------------:|:--------:|:----------:|\n`;
  out += `| **${slugs.length}** | **${totalCompleted}** | **${totalTopics}** | **${overallPct}%** |\n\n`;
  out += `</div>\n\n---\n\n`;

  slugs.forEach((slug, idx) => {
    const r = store[slug];
    const emoji = getRoadmapEmoji(slug);
    const pct = r.progressPercent;

    out += `### ${emoji} ${r.displayName} — ${pct}% complete\n`;
    out += `![Progress](${getBarUrl(pct, `${pct}%`)})\n\n`;
    out += `<details>\n`;
    out += `<summary>✅ ${r.completed} topics completed — click to expand</summary>\n\n`;
    out += `| Topic | Committed |\n`;
    out += `|-------|-----------|\n`;
    r.committedSlugs.forEach(topicSlug => {
      out += `| [${unslugify(topicSlug)}](${slug}/${topicSlug}.md) | ${r.lastCommitDate} |\n`;
    });
    out += `\n</details>\n\n`;
    if (idx < slugs.length - 1) out += `---\n\n`;
  });

  out += `<!-- ROADMAPHUB:DASHBOARD:END -->`;
  return out;
}

function getBarUrl(pct: number, label: string): string {
  const encoded = encodeURIComponent(label);
  if (pct < 25) return `https://geps.dev/progress/${pct}?dangerColor=ef4444&barColor=ef4444&label=${encoded}`;
  if (pct < 50) return `https://geps.dev/progress/${pct}?barColor=f97316&label=${encoded}`;
  if (pct < 75) return `https://geps.dev/progress/${pct}?barColor=eab308&label=${encoded}`;
  return `https://geps.dev/progress/${pct}?barColor=22c55e&label=${encoded}`;
}

function getRoadmapEmoji(slug: string): string {
  const map: Record<string, string> = {
    'backend': '⚙️', 'frontend': '🎨', 'devops': '🚀', 'full-stack': '🌐',
    'react': '⚛️', 'nodejs': '💚', 'node.js': '💚', 'python': '🐍',
    'java': '☕', 'docker': '🐳', 'kubernetes': '☸️', 'aws': '☁️',
    'linux': '🐧', 'javascript': '🟨', 'typescript': '🔷', 'golang': '🐹',
    'rust': '🦀', 'sql': '🗄️', 'mongodb': '🍃', 'postgresql-dba': '🐘',
    'redis': '🔴', 'cyber-security': '🔒', 'machine-learning': '🤖',
    'ai-engineer': '🧠', 'system-design': '🏗️', 'computer-science': '💻',
    'angular': '🔴', 'vue': '💚', 'nextjs': '▲', 'flutter': '💙',
    'android': '🤖', 'ios': '🍎', 'swift-ui': '🍎', 'kotlin': '🟣',
    'spring-boot': '🌿', 'django': '🟩', 'laravel': '🔴', 'php': '🐘',
    'graphql': '🩷', 'terraform': '🟪', 'cloudflare': '🟠',
    'blockchain': '⛓️', 'game-developer': '🎮', 'ux-design': '🎭',
    'ai-agents': '🤖', 'prompt-engineering': '✨',
  };
  return map[slug] || '📘';
}
